### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by BrasilianZ** [bruxo00/bAntiCheat#2]
Eu testei o sistema em Windows e funcionou. passei para minha VPS Linux e deu erro em socket connect. parece ser algo relacionado a TCP e UDP, tem como resolver isso?

**Comment by BrasilianZ** [comment]
...

**Comment by diogomartino** [comment]
Provavelmente o erro terá a ver com portas fechadas quer na parte do cliente.

**Comment by BrasilianZ** [comment]
Eu devo liberar a porta 4000 no Linux ?

**Comment by BrasilianZ** [comment]
Se sim, podem e dizer como liberá-la ?

**Comment by BrasilianZ** [comment]
?

**Comment by Edresson** [comment]
Olá, Primeiramente se você quiser usar o sistema deverá fazer um site com uma base de dados,mysql,sqlite, a qual preferir, e após isso fazer a conexão reversa vindo do client para o servidor, as portas do client, ou seja de seu jogador, normalmente são fechadas , logo não é possivel connectar do servidor para o client ... 
Você deve editar o Client e adicionar um requisiçao para seu site/base de dados , apartir dai fazer a verificação se o client está sem cheat ou não, conexão de servidor para o client não irá funcionar ! 

Recomendo ao desenvolvedor que faça isso, crie uma base de dados, um simples script que gere as tabelas, após crie uma pequena API, na qual o cliente usará para enviar a mensagem para o servidor !

**Comment by diogomartino** [comment]
@BrasilianZ Este anticheat foi uma experiência minha com sockets. A maneira como o anti cheat está construído não é a melhor. Um dos problemas é que o cliente é o server na parte dos sockets, o que requer que ele tenha portas abertas para funcionar bem. Mas eu fiz assim por simplicidade, pois o meu objetivo não era criar um anticheat para ser usado pelas pessoas, mas para fins de estudo.

A sugestão do @Edresson é mais simples de ser feita, mas também é menos robusta. Uma conexão direta servidor > cliente é muito mais eficaz do que andar com databases. Um anticheat com sockets eficiente seria estando a parte do servidor dos sockets no servidor, não sendo preciso assim abrir portas nenhumas no cliente.

Eu estou a pensar fazer um remake deste anticheat, mas já com outro tipo de segurança e rapidez.
